import os
from pathlib import Path
from typing import Any, Iterable

from fpdf import FPDF

REPORTS_DIR = Path(__file__).resolve().parents[1] / "generated_reports"
os.makedirs(REPORTS_DIR, exist_ok=True)


class NuanceReport(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 16)
        self.set_text_color(0, 51, 102)
        self.cell(0, 10, "NuanceNode Investigative Report", border=False, ln=True, align="C")
        self.set_draw_color(0, 51, 102)
        self.line(10, 22, 200, 22)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by NuanceNode AI", align="C")


def _safe_text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value.strip()
    return str(value).strip()


def _latin_safe(value: Any) -> str:
    return _safe_text(value).encode("latin-1", "replace").decode("latin-1")


def _listify(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    if isinstance(value, set):
        return list(value)
    if value == "":
        return []
    return [value]


def _format_kv_block(data: dict[str, Any], preferred_order: Iterable[str] | None = None) -> str:
    lines: list[str] = []
    used_keys: set[str] = set()

    if preferred_order:
        for key in preferred_order:
            if key in data:
                used_keys.add(key)
                formatted = _format_value_for_section(key, data.get(key))
                if formatted:
                    lines.append(formatted)

    for key, value in data.items():
        if key in used_keys:
            continue
        formatted = _format_value_for_section(key, value)
        if formatted:
            lines.append(formatted)

    return "\n".join(lines).strip()


def _format_value_for_section(key: str, value: Any) -> str:
    label = key.replace("_", " ").title()

    if isinstance(value, dict):
        nested = _format_kv_block(value)
        return f"{label}:\n{nested}" if nested else ""

    if isinstance(value, list):
        items = []
        for item in value:
            if isinstance(item, dict):
                nested = _format_kv_block(item)
                if nested:
                    items.append(f"- {nested}")
            else:
                text = _safe_text(item)
                if text:
                    items.append(f"- {text}")
        return f"{label}:\n" + "\n".join(items) if items else ""

    text = _safe_text(value)
    return f"{label}: {text}" if text else ""


def _add_section(pdf: NuanceReport, title: str, content: Any):
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, _latin_safe(title), ln=True)
    pdf.set_font("helvetica", "", 11)
    pdf.set_text_color(50, 50, 50)

    if isinstance(content, dict):
        text = _format_kv_block(content)
    elif isinstance(content, list):
        lines = []
        for item in content:
            if isinstance(item, dict):
                nested = _format_kv_block(item)
                if nested:
                    lines.append(f"- {nested}")
            else:
                item_text = _safe_text(item)
                if item_text:
                    lines.append(f"- {item_text}")
        text = "\n".join(lines)
    else:
        text = _safe_text(content)

    safe_content = _latin_safe(text or "N/A")
    pdf.multi_cell(0, 7, safe_content)
    pdf.ln(5)


def _add_context_tree_section(pdf: NuanceReport, title: str, items: list[Any], color: tuple[int, int, int]):
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(*color)
    pdf.cell(0, 10, _latin_safe(title), ln=True)

    if not items:
        _add_section(pdf, "Summary", "No structured arguments were available.")
        return

    for item in items:
        if isinstance(item, dict):
            label = item.get("weight", "N/A")
            reason_text = f"Reason: {_safe_text(item.get('reason'))}"
            explanation = _safe_text(item.get("explanation"))
            evidence = _safe_text(item.get("evidence"))

            if explanation:
                reason_text += f"\nExplanation: {explanation}"
            if evidence:
                reason_text += f"\nEvidence: {evidence}"

            _add_section(pdf, f"- {label} Weight", reason_text)
        else:
            _add_section(pdf, "- Argument", _safe_text(item))


def generate_pdf_report(chat_id: int, claim: str, report_data: dict) -> Path:
    pdf = NuanceReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Analyzed Claim:", ln=True)
    pdf.set_font("helvetica", "I", 12)
    pdf.multi_cell(0, 7, f'"{_latin_safe(claim)}"')
    pdf.ln(5)

    verdict = _safe_text(report_data.get("verdict", "Unknown")) or "Unknown"
    confidence = report_data.get("confidence_score", 0)

    pdf.set_font("helvetica", "B", 14)
    if "false" in verdict.lower() or "fake" in verdict.lower():
        pdf.set_text_color(200, 0, 0)
    elif "unverified" in verdict.lower() or "misleading" in verdict.lower():
        pdf.set_text_color(180, 120, 0)
    else:
        pdf.set_text_color(0, 128, 0)

    pdf.cell(0, 10, _latin_safe(f"Verdict: {verdict} (Confidence: {confidence}%)"), ln=True)
    pdf.ln(5)

    facts_section = report_data.get("facts", "N/A")
    sources_section = report_data.get("sources", "N/A")
    logic_section = report_data.get("logic_analysis", "N/A")
    anatomy_section = report_data.get("anatomy_of_belief", "N/A")
    meta_section = report_data.get("meta", {})

    _add_section(pdf, "1. Facts Node", facts_section)
    _add_section(pdf, "2. Sources Node", sources_section)
    _add_section(pdf, "3. Logic Node", logic_section)
    _add_section(pdf, "4. Anatomy Node", anatomy_section)

    if meta_section:
        _add_section(
            pdf,
            "5. Analysis Metadata",
            meta_section,
        )

    context_tree = report_data.get("context_tree", {})
    if context_tree:
        pdf.add_page()
        pdf.set_font("helvetica", "B", 14)
        pdf.set_text_color(0, 51, 102)
        pdf.cell(0, 10, "The Context Tree Analysis", ln=True)
        pdf.ln(5)

        _add_context_tree_section(
            pdf,
            "Arguments For (Why it may be TRUE):",
            _listify(context_tree.get("why_it_may_be_true")),
            (0, 128, 0),
        )

        _add_context_tree_section(
            pdf,
            "Arguments Against (Why it may be FALSE):",
            _listify(context_tree.get("why_it_may_be_false")),
            (200, 0, 0),
        )

        belief_drivers = context_tree.get("belief_drivers")
        if belief_drivers:
            _add_section(pdf, "Belief Drivers", belief_drivers)

    file_path = REPORTS_DIR / f"NuanceNode_Report_{chat_id}.pdf"
    pdf.output(str(file_path))
    return file_path
