import os
from fpdf import FPDF

REPORTS_DIR = "generated_reports"
os.makedirs(REPORTS_DIR, exist_ok=True)

class NuanceReport(FPDF):
    def header(self):
        # Professional Header
        self.set_font("helvetica", "B", 16)
        self.set_text_color(0, 51, 102) # Dark Blue
        self.cell(0, 10, "NuanceNode Investigative Report", border=False, ln=True, align="C")
        self.set_draw_color(0, 51, 102)
        self.line(10, 22, 200, 22)
        self.ln(10)

    def footer(self):
        # Footer with page numbers
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by NuanceNode AI", align="C")

def generate_pdf_report(chat_id: int, claim: str, report_data: dict) -> str:
    """JSON data ko ek beautiful PDF mein convert karta hai"""
    pdf = NuanceReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    def add_section(title, content):
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, title, ln=True)
        pdf.set_font("helvetica", "", 11)
        pdf.set_text_color(50, 50, 50)
        # Handle special characters gracefully
        safe_content = str(content).encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 7, safe_content)
        pdf.ln(5)

    # 1. Claim & Verdict Section
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 10, "Analyzed Claim:", ln=True)
    pdf.set_font("helvetica", "I", 12)
    pdf.multi_cell(0, 7, f'"{claim.encode("latin-1", "replace").decode("latin-1")}"')
    pdf.ln(5)

    verdict = report_data.get("verdict", "Unknown")
    confidence = report_data.get("confidence_score", 0)
    
    pdf.set_font("helvetica", "B", 14)
    if "Fake" in verdict or "False" in verdict:
        pdf.set_text_color(200, 0, 0) # Red for Fake
    else:
        pdf.set_text_color(0, 128, 0) # Green for True
        
    pdf.cell(0, 10, f"Verdict: {verdict} (Confidence: {confidence}%)", ln=True)
    pdf.ln(5)

    # 2. The 4 Nodes Section
    add_section("1. Facts Node (Raw Data):", report_data.get("facts", "N/A"))
    add_section("2. Sources Node (Media Consensus):", report_data.get("sources", "N/A"))
    add_section("3. Logic & Fallacies Node:", report_data.get("logic_analysis", "N/A"))
    add_section("4. Anatomy of Belief Node:", report_data.get("anatomy_of_belief", "N/A"))

    # 3. Context Tree Section (New Page)
    context_tree = report_data.get("context_tree", {})
    if context_tree:
        pdf.add_page()
        pdf.set_font("helvetica", "B", 14)
        pdf.set_text_color(0, 51, 102)
        pdf.cell(0, 10, "The Context Tree Analysis", ln=True)
        pdf.ln(5)

        # Arguments FOR
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(0, 128, 0)
        pdf.cell(0, 10, "Arguments For (Why it may be TRUE):", ln=True)
        for item in context_tree.get("why_it_may_be_true", []):
            add_section(f"- {item.get('weight', 'N/A')} Weight:", f"Reason: {item.get('reason')}\nEvidence: {item.get('evidence')}")

        # Arguments AGAINST
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(200, 0, 0)
        pdf.cell(0, 10, "Arguments Against (Why it may be FALSE):", ln=True)
        for item in context_tree.get("why_it_may_be_false", []):
            add_section(f"- {item.get('weight', 'N/A')} Weight:", f"Reason: {item.get('reason')}\nEvidence: {item.get('evidence')}")

    # Save the file
    file_path = os.path.join(REPORTS_DIR, f"NuanceNode_Report_{chat_id}.pdf")
    pdf.output(file_path)
    return file_path